sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  alioss:
    endpoint: oss-cn-shanghai.aliyuncs.com
    access-key-id: LTAI5tMNBWdpkKkEFpggBbXG
    access-key-secret: yF3rwx4Ei2bRjdIGbtNQs0ORfwPIQe
    bucket-name: big-event20050721
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 0
  wechat:
    appid: wx3061df9acf48ce24
    secret: ae07f3426770ff1ed8300590d805a3c1